### ISSUE TITLE
Is there a convention for shipping npm packages that play nicely with this plugin?

### ISSUE THREAD

**Issue by madelson** [privatenumber/webpack-localize-assets-plugin#18]
## Is your feature request related to a problem? Please describe.

We have a number of internal npm packages which contain translations (e. g. think tooltips in a common widget). It would be nice if those packages could be set up in a way that they would "just work" for someone using this plugin but also wouldn't completely break for a consumer who was not using it.

## Describe the solution you'd like
I'm imagining something like this:

```
// in index.js in the package

function __(key) { return null; } // fallback definition for __ if plugin not in use

// messages is an optional argument containing the translations lookup dictionary. 
// Doesn't need to be provided if the plugin is in use
export function doStuff(messages) {
    // Note that I'm using the package name as the key prefix to avoid collisions with keys in other packages
    // and in the application itself.
    const localizedString = __("@scope/packageName.keyName") || translations.keyName
    ...
};

// in webpack-localize-assets-plugin.json shipped alongside index.js. In my ideal world the plugin would pick this up by default
{
    "en-US": { "@scope/packageName.keyName": "foo" }
     ...
}
```

## Describe alternatives you've considered

I imagine that this could be built on top of the plugin, although one thing that would get tricky is if multiple versions of a translated package are included in the compilation as nested modules since we'd need to make sure to use the correct json file.

Thoughts?

**Comment by privatenumber** [comment]
I can't tell if there's a proposal here (given it's a feature request rather than a discussion question), but to answer the issue question, there is no convention.

There is no way to provide a fallback function at run-time because Webpack's static analysis requires that the localize function is a global. However, the consuming app can add fallback logic via the new [localizeCompiler](https://github.com/privatenumber/webpack-localize-assets-plugin#localizecompiler) API.

You can ship a package with translation JSONs, and your consuming app build can merge them with the apps translation JSONs before passing it into this plugin.
