### ISSUE TITLE
Pluralisation and templating support

### ISSUE THREAD

**Issue by benjamin-hodgson** [privatenumber/webpack-localize-assets-plugin#20]
I'm interested in using `webpack-localize-assets-plugin` to replace our (Stack Overflow's) homemade localisation system. Our existing system has built-in support for string templating - you write code like

```javascript
__("$username$ sent you a message", { username: sender.name })
```

and at runtime the localisation system will return something like `Benjamin sent you a message`. This is important to us because the target language's grammar might require that the words in the sentence be moved around.

Our localisation system also supports pluralisation through a magic `$count$` template variable:

```javascript
__("$count$ widgets", { count: widgets.length })
```

will return `1 widget` or `12 widgets`, or an equivalent one/many pluralisation in the target language. (Again, the target language's grammar may require a different structure for plural sentences.)

Does `webpack-localize-assets-plugin` have a clean way to do these out of the box? I've considered an API like

```javascript
formatString(__("$username$ sent you a message"), { username: sender.name })
```

for the first case - the syntax is a bit messy but it should work. I can't think of a clean way to do pluralisation though - not without changing the plugin itself or building a (messy) code rewriting shim.

Would you accept a pull request adding an API for either of these cases?

**Comment by privatenumber** [comment]
Thanks for your issue @benjamin-hodgson!

#### RE: templating
In my use-cases, I also swapped out the variables post-localization as you considered with:
```ts
formatString(__("$username$ sent you a message"), { username: sender.name })
```

To support an API like this:
```ts
__("$username$ sent you a message", { username: sender.name })
```

the plugin would have to compile it to something like this because `sender.name` can only be resolved at run-time.
```ts
"$username$ sent you a message".replace('$username$', sender.name)
```


#### RE: pluralisation
I think this would depend on what your source of pluralisation data looks like.

Assuming your localization system does not automate pluralisation, I'll guess the i18n system outputs something like:
```json5
{
	singular: "$count$ widget", // 1
	plural: "$count$ widgets", // 0, or 2 & more
}
```

Similar to the examples [here](https://www.i18next.com/translation-function/plurals).

-----


To address both, I think it makes sense to add a `localizationCompiler` option that takes in a function that compiles `__(string, data)` to run-time code.

This function can use any micro-template compiler to convert the string to run-time code:

```ts
import { compile } from 'eta'

function localizationCompiler(localizedString, data) {
	if (!data) {
		return JSON.stringify(localizedString)
	}

	return compile(localizedString) + `(${JSON.stringify(data)})`
}
```

If pluralization data looks like the above:

```ts
localizedData = {
	singular: "$count$ widget", // 1
	plural: "$count$ widgets", // 0, or 2 & more
}

function localizationCompiler(localizedData, data) {
	if (!data) {
		return JSON.stringify(localizedData.singular)
	}
	
	const count = Object.entries(data)[0]

	let localizedString
	if (count === 0 || count > 1) {
		localizedString = localizedData.plural
	} else {
		localizedString = localizedData.singular
	}

	return compile(localizedString) + `(${JSON.stringify(data)})`
}
```

Template engines I looked at:
- https://github.com/eta-dev/eta
- https://github.com/squirrellyjs/squirrelly
- https://github.com/premasagar/tim
- https://github.com/sindresorhus/pupa
- https://github.com/lukeed/tempura
- https://github.com/mozilla/nunjucks


What do you think?

**Comment by privatenumber** [comment]
Oh yes, you're right! Sorry about that. 😅

PR welcome!

**Comment by ethanius** [comment]
Hello, I am just trying to find out how to do this with this plugin at all and have to tell you - singular/plural is not enough for some languages. For example in czech it is different for 0, 1, 2-4, 5+ (where 0 and 5+ is usually the same but not necessarily). We use a custom solution now, but AFAIK it is based on messageformat.

For example:
```
{
"statsHelped": "Pomohl {total} {total, plural, one{fotkou} few{fotkami} other{fotkami}}",
}
```

Calling that in code:

```
_('statsHelped', { total: 1253 });
```

That translates to 1, 2-4 (few), and other covers 0 and 5+, because it is not 1 or 2-4. The system also enables writing something like `=value`, eg. `=0` or `=42` to cover any specific exception from the other rules. Pretty robust. Singular/plural is highly insufficient to be really used in production.

**Comment by privatenumber** [comment]
Thanks for your insight @ethanius .

We're moving forward with an API where you can pass in your own logic to handle pluralization so it would be up to the user to handle that.

**Comment by benjamin-hodgson** [comment]
@privatenumber I thought you might be pleased to hear that I shipped this to production today! We're now using your plugin across our localised Stack Overflow sites (eg [japanese](https://ja.stackoverflow.com/), [russian](https://ru.stackoverflow.com/), etc. Thank you very much for all your hard work!

**Comment by privatenumber** [comment]
Wow, that just made my day! 😄
Thanks for using the plugin and contributing your hard work! It was a pleasure collaborating with you @benjamin-hodgson
